"""Workspace tools for the e2b sandbox (block 18).

These tools run on the HOST and call the sandbox filesystem / commands APIs.
They give the agent persistent file storage and shell access inside the sandbox:
- run_command       — execute a shell command
- write_sandbox_file — create / overwrite a text file
- read_sandbox_file  — read a text file
- list_sandbox_files — list directory contents

All four tools require ``context.code_env`` (an e2b AsyncSandbox) to be set,
i.e. the Agent must be initialised with ``code_execution='e2b'``.
"""
from __future__ import annotations

import json

from agentkit.context import ExecutionContext
from agentkit.tools.base import tool

_NO_SANDBOX = "Requires Agent(code_execution='e2b')."


@tool
async def run_command(
    context: ExecutionContext,
    cmd: str,
    cwd: str | None = None,
) -> str:
    """Run a shell command inside the sandbox and return its output.

    Use for installing packages, running scripts, checking files, compiling
    code, git operations, or any operation that needs a real shell.

    Parameters
    ----------
    cmd : str
        Shell command to run, e.g. ``"pip install pandas"`` or ``"ls -la"``.
    cwd : str | None
        Working directory inside the sandbox.  Default: ``/home/user``.

    Returns (JSON)
    --------------
    ``{"stdout": "...", "stderr": "...", "exit_code": 0}``
    Non-zero exit_code means the command failed; stderr contains details.
    """
    if context.code_env is None:
        raise RuntimeError(f"run_command: no sandbox. {_NO_SANDBOX}")
    kwargs: dict = {"timeout": 60}
    if cwd is not None:
        kwargs["cwd"] = cwd
    result = await context.code_env.commands.run(cmd, **kwargs)
    return json.dumps(
        {
            "stdout": result.stdout or "",
            "stderr": result.stderr or "",
            "exit_code": result.exit_code,
        },
        ensure_ascii=False,
    )


@tool
async def write_sandbox_file(
    context: ExecutionContext,
    path: str,
    content: str,
) -> str:
    """Write a text file inside the sandbox.

    The file persists for the duration of the sandbox (the current agent run).
    Subsequent ``execute_python`` or ``run_command`` calls can read it.

    Parameters
    ----------
    path : str
        Destination path, e.g. ``"/home/user/data.csv"``.  Parent directories
        are created automatically.
    content : str
        UTF-8 text to write.

    Returns
    -------
    Confirmation string: ``"OK: wrote <N> bytes to <path>"``.
    """
    if context.code_env is None:
        raise RuntimeError(f"write_sandbox_file: no sandbox. {_NO_SANDBOX}")
    await context.code_env.files.write(path, content)
    return f"OK: wrote {len(content.encode())} bytes to {path}"


@tool
async def read_sandbox_file(
    context: ExecutionContext,
    path: str,
) -> str:
    """Read a text file from the sandbox and return its contents.

    Use this to inspect output files, logs, or data written by
    ``write_sandbox_file`` or generated by ``execute_python`` / ``run_command``.

    Parameters
    ----------
    path : str
        Path to the file inside the sandbox, e.g. ``"/home/user/output.txt"``.

    Returns
    -------
    File contents as a UTF-8 string.
    """
    if context.code_env is None:
        raise RuntimeError(f"read_sandbox_file: no sandbox. {_NO_SANDBOX}")
    return await context.code_env.files.read(path, format="text")


@tool
async def list_sandbox_files(
    context: ExecutionContext,
    path: str = "/home/user",
) -> str:
    """List files and directories inside the sandbox.

    Parameters
    ----------
    path : str
        Directory to list.  Default: ``/home/user``.

    Returns (JSON)
    --------------
    Array of ``{"name": "...", "type": "file"|"dir"|"symlink", "path": "..."}``.
    """
    if context.code_env is None:
        raise RuntimeError(f"list_sandbox_files: no sandbox. {_NO_SANDBOX}")
    entries = await context.code_env.files.list(path)
    return json.dumps(
        [
            {
                "name": e.name,
                "type": e.type.value if e.type is not None else "unknown",
                "path": e.path,
            }
            for e in entries
        ],
        ensure_ascii=False,
    )


# Convenience list for Agent(workspace=True)
WORKSPACE_TOOLS: list = [run_command, write_sandbox_file, read_sandbox_file, list_sandbox_files]
